apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      run: apache
  replicas: 2
  template:
    metadata:
      labels:
        run: apache
    spec:
      containers:
      - name: apache
        image: ubuntu/apache2:2.4-22.04_beta
        ports:
        - containerPort: 80
